application: blinx-1143
version: 3
runtime: php55
api_version: 1
threadsafe: yes

env_variables:
  app_context: /

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: /fb-callback.php
  script: fb-callback.php

- url: /google-callback.php
  script: google-callback.php

- url: /detailreg-user.php
  script: detailreg-user.php

- url: .*
  script: index.php

# Skip non deployable files.
skip_files:
- dbscripts/
- form-1/
- README.md
- .DS_Store
