application: blinx
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: .*
  script: php/index.php
